# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 21:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='daate_of_birth',
            new_name='date_of_birth',
        ),
    ]
